version: "3"

services:
  web:
    build: .
    container_name: bot
    environment:
      - TG_BOT_TOKEN=${TG_BOT_TOKEN}
    command: python app.py
    ports:
      - 80:80
    volumes:
      - ./:/app